Status code check not working
Also, added in a check for extraneous keys in the test script.

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -4,7 +4,7 @@
 ./start_server
 . venv/bin/activate
 
-TEST_1="$(imprimatur tests/1/test_1.py)"
+TEST_1="$(imprimatur tests/1/test.py)"
 
 TEST_1_DES="Name: single regex failure
 Request: http://localhost:5000/text_1
@@ -19,17 +19,17 @@ The best of all possible worlds."
 if [[ "$TEST_1" != "$TEST_1_DES" ]]
   then
     echo -e "Test 1 failed.\n$TEST_1" 
-    exit
+    exit 1
 fi
 
-if imprimatur tests/1/test_1.py > /dev/null
+if imprimatur tests/1/test.py > /dev/null
   then
     echo "Test 1 should fail, but it returned success."
-    exit
+    exit 1
 fi
 echo "Passed Test 1"
 
-TEST_2="$(imprimatur tests/2/test_2.py)"
+TEST_2="$(imprimatur tests/2/test.py)"
 TEST_2_DES="Name: single regex success
 Request: http://localhost:5000/text_2
 Name: Auth success
@@ -51,17 +51,17 @@ Passed all tests!"
 if [[ "$TEST_2" != "$TEST_2_DES" ]]
   then
     echo -e "Test 2 failed.\n$TEST_2" 
-    exit
+    exit 1
 fi
 
-if ! imprimatur tests/2/test_2.py > /dev/null
+if ! imprimatur tests/2/test.py > /dev/null
   then
     echo "Test 2 should return success, but it returned fail."
-    exit
+    exit 1
 fi
 echo "Passed Test 2"
 
-TEST_3="$(imprimatur tests/3/test_3.py)"
+TEST_3="$(imprimatur tests/3/test.py)"
 
 TEST_3_DES="Name: Auth failure
 Request: http://localhost:5000/auth
@@ -76,14 +76,39 @@ not authorized"
 if [[ "$TEST_3" != "$TEST_3_DES" ]]
   then
     echo -e "Test 3 failed.\n$TEST_3" 
-    exit
+    exit 1
 fi
 
-if imprimatur tests/3/test_3.py > /dev/null
+if imprimatur tests/3/test.py > /dev/null
   then
     echo "Test 3 should fail, but it returned success."
-    exit
+    exit 1
 fi
 echo "Passed Test 3"
+
+TEST_4="$(imprimatur tests/4/test.py)"
+
+TEST_4_DES="Name: Response code failure
+Request: http://localhost:5000/text_1
+The desired status code 302 doesn't match the actual status code 200.
+('content-length', '32')
+('content-type', 'text; charset=utf-8')
+('date', 'Sat, 17 Jan 2015 13:30:54 GMT')
+('server', 'Werkzeug/0.9.6 Python/3.4.0')
+
+The best of all possible worlds."
+
+if [[ "$TEST_4" != "$TEST_4_DES" ]]
+  then
+    echo -e "Test 4 failed.\n$TEST_4" 
+    exit 1
+fi
+
+if imprimatur tests/4/test.py > /dev/null
+  then
+    echo "Test 4 should fail, but it returned success."
+    exit 1
+fi
+echo "Passed Test 4"
 
 echo "Passed All!!"
